#!/bin/bash
while read oldrev newrev ref
do
  if [[ $ref =~ .*/master$ ]]; then
    echo "Master ref received. Deploying master branch to production..."
    git --work-tree=/home/appuser/DE2_proj/Production --git-dir=/home/appuser/my_project checkout -f
  else
    echo "Ref $ref successfully received. Doing nothing: only the master branch may be deployed on this server."
  fi
done