version: "3.9"

services:
  web:
    build:
      context: .
    container_name: flask_app
    volumes:
      - .:/app
    ports:
      - "5100:5100"
    depends_on:
      - rabbit

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    hostname: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  worker_1:
    build:
      context: .
    container_name: worker_1
    volumes:
      - .:/app
    entrypoint: celery
    command: -A worker worker --loglevel=debug
    depends_on:
      - rabbit
